# .github/workflows/pages.yml

name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Removed cache: 'npm' to avoid searching for lock file in root

      - name: Install dependencies
        working-directory: ./nutriaid  # Set the working directory to nutriaid
        run: npm ci  # Now it will run from the nutriaid folder

      - name: Build
        working-directory: ./nutriaid  # Build from the nutriaid directory
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './nutriaid/dist'  # Adjust path to point to dist folder inside nutriaid

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Corrected syntax by removing extra text
